[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
overlay = { path = "../overlay" }

log = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
palette = { workspace = true }
dirs = { workspace = true }
notify = { workspace = true }
shell-words = { workspace = true }

anyhow = { workspace = true }
tokio-stream = { workspace = true }
ashpd = { workspace = true }
x11rb = { workspace = true }
#xcap = { workspace = true}
xkbcommon = { workspace = true }

[features]
clap = ["overlay/clap", "lib/clap"]