[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
overlay = { path = "../overlay" }

log = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

env_logger = { workspace = true }
anyhow = {  workspace = true }
ashpd = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
x11rb = { workspace = true }
#xcap = { workspace = true}
