[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }

image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

env_logger = { version = "0.11.8" }
anyhow = { version = "1.0.100" }
ashpd = { version = "0.12.0", features = ["wayland"] }
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["full"] }
x11rb = { version = "0.13.2" }
xcap = "0.7.1"
