[package]
name = "wf_fissure_price"
version = "0.1.0"
edition = "2024"

[dependencies]
# Library
lazy_static = "1.5.0"
thiserror = "2.0.17"
image = "0.25.9"
tesseract = "0.15.2"
rayon = "1.11.0"
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
palette = "0.7.6"
levenshtein = "1.0.5"
serde_json = "1.0.145"
serde-aux = "4.7.0"

# Binary (Will probably be seperated into its own crate)
env_logger = { version = "0.11.8", optional = true }
anyhow = { version = "1.0.100", optional = true }
ashpd = { version = "0.12.0", optional = true, features = ["wayland"] }
tokio = { version = "1.48.0", optional = true, features = ["full"] }
tokio-stream = { version = "0.1.17", optional = true, features = ["full"] }
x11rb = { version = "0.13.2", optional = true }

[dev-dependencies]
colored = "3.0.0"

[features]
default = ["x11", "wayland"]
bin = [
    "dep:env_logger",
    "dep:anyhow",
    "dep:tokio",
    "dep:tokio-stream"
]
x11 = ["dep:x11rb"]
wayland = ["dep:ashpd"]