[package]
name = "wf_fissure_price"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
wf_fissure_price_lib = { path = "lib" }
colored = "3.0.0"
anyhow = "1.0.100"

[features]

[workspace]
members = ["bin", "cli", "lib"]
